language: python

python:
  - 2.7
  - 3.6

cache: pip

notifications:
  email:
    - code@lbolla.info

# TravisCI does not handle numpy/scipy well: https://gist.github.com/dan-blanchard/7045057

before_install:
  - export PYMAJORVER=`python -c "import sys; print(sys.version_info.major)"`
  - wget http://repo.continuum.io/miniconda/Miniconda$PYMAJORVER-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda$PYMAJORVER/bin:$PATH
  - conda update --yes conda

install:
  # Make sure the versions here match what we have in requirements.txt
  - conda install --yes python=$TRAVIS_PYTHON_VERSION "numpy<2" "scipy<2" "matplotlib<4" "python-dateutil<3"
  - pip install -r requirements.txt

script: python setup.py test

deploy:
  provider: pypi
  user: lbolla
  python: 3.6
  password:
    secure: "aBHsueBZZtO3n+WfhbEfKlps+dHN+Y6tj7kJ1Nj6FFt75ats2SLzByuR07uwnHYr+HLgauExNxwJoxYvIIRvTMbbVJ3uBENpjSWwes8xGrNwOJ0ohcnp1xmW/4jV2+UJ0j/SmZQXk/BcxI7tvLyAlFNZ8CQHBllWlRUzOXGstuw="
  on:
    tags: true
