[build-system]
requires = [
  "setuptools>=61",
  "wheel",
  "setuptools_scm>=7",
]
build-backend = "setuptools.build_meta"

[project]
name = "ElectroMagneticPython"
dynamic = ["version"]
requires-python = ">=3.10"

[tool.flake8]
max-line-length = 130
ignore = ["E203", "E741", "E501"]
